controller: add id for policy (#41)
* controller: add id for policy

Signed-off-by: weizhou.lan@daocloud.io <weizhou.lan@daocloud.io>

* controller: add id for policy

Signed-off-by: weizhou.lan@daocloud.io <weizhou.lan@daocloud.io>

* controller: add id for policy

Signed-off-by: weizhou.lan@daocloud.io <weizhou.lan@daocloud.io>

* controller: add id for policy

Signed-off-by: weizhou.lan@daocloud.io <weizhou.lan@daocloud.io>

* controller: add id for policy

Signed-off-by: weizhou.lan@daocloud.io <weizhou.lan@daocloud.io>

---------

Signed-off-by: weizhou.lan@daocloud.io <weizhou.lan@daocloud.io>

diff --git a/tests/Makefile b/tests/Makefile
--- a/tests/Makefile
+++ b/tests/Makefile
@@ -18,7 +18,6 @@ init_vagrant: installE2eTools clean
 		  KUBECONFIG_PATH=$(E2E_KUBECONFIG_PATH) \
 		  VAGRANT_IMAGE_K8S=$(E2E_VAGRANT_IMAGE_K8S) \
 		  VAGRANT_IMAGE_UBUNTU=$(E2E_VAGRANT_IMAGE_UBUNTU) \
-		  SKIP_KUBE_PROXY=$(E2E_SKIP_KUBE_PROXY) \
 		  ./setupCluster.sh on
 	@echo "===================== deploy prometheus CRD ========== "
 	# https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/main/example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml ; } \
@@ -31,6 +30,9 @@ init_vagrant: installE2eTools clean
 	kubectl apply --kubeconfig $(E2E_KUBECONFIG_PATH) -f ./crd/monitoring.coreos.com_probes.yaml
 	# https://raw.githubusercontent.com/grafana-operator/grafana-operator/master/deploy/manifests/latest/crds.yaml  ; } \
 	kubectl apply --kubeconfig $(E2E_KUBECONFIG_PATH) -f ./crd/grafanadashboards.yaml
+	if [ "$(E2E_SKIP_KUBE_PROXY)" == "true" ] ; then \
+  			make uninstall_kube_proxy ; \
+  		fi
 	@echo "========================================================"
 	@echo "   export KUBECONFIG=$(E2E_KUBECONFIG_PATH)             "
 	@echo "   kubectl get pod -o wide -A                           "
@@ -192,6 +194,7 @@ deploy_project:
 
 .PHONY: uninstall_kube_proxy
 uninstall_kube_proxy:
+	KUBECONFIG=$(E2E_KUBECONFIG_PATH) ./scripts/uninstallKubeProxy.sh
 
 
 .PHONY: install_example_app
@@ -259,10 +262,12 @@ test_connectivity:
 	export K8S_PROXY_SERVER_MAPPING_PORT=$(E2E_HOSTPORT_WORKERVM_PROXY_SERVER) ; \
  		export HOST_PROXY_SERVER_MAPPING_PORT=$(E2E_HOSTPORT_HOSTVM_PROXY_SERVER) ;\
  		export KUBECONFIG=$(E2E_KUBECONFIG_PATH) ; \
- 		./scripts/testAppConnectivity.sh basic || { echo "failed to test the connectivity" ; exit 1 ; } ;  \
-	    ./scripts/testAppConnectivity.sh service || { echo "failed to test the connectivity" ; exit 1 ; } ; \
-	    ./scripts/testAppConnectivity.sh balancing || { echo "failed to test the connectivity" ; exit 1 ; } ; \
-	    ./scripts/testAppConnectivity.sh redirect || { echo "failed to test the connectivity" ; exit 1 ; }
+		FAILURE=0 ; \
+ 		./scripts/testAppConnectivity.sh basic || { echo "failed to test the connectivity" ; ((FAILURE+=1)) ;  } ;  \
+	    ./scripts/testAppConnectivity.sh service || { echo "failed to test the connectivity" ; ((FAILURE+=1)) ; } ; \
+	    ./scripts/testAppConnectivity.sh balancing || { echo "failed to test the connectivity" ; ((FAILURE+=1)) ; } ; \
+	    ./scripts/testAppConnectivity.sh redirect || { echo "failed to test the connectivity" ; ((FAILURE+=1)) ; }  ;\
+	    ((FAILURE==0)) || { echo "error: some tests failed" ; exit 1 ; }
 
 
 .PHONY: clean
