test app
Signed-off-by: weizhou.lan@daocloud.io <weizhou.lan@daocloud.io>

diff --git a/tests/vagrant/ssh b/tests/vagrant/ssh
--- a/tests/vagrant/ssh
+++ b/tests/vagrant/ssh
@@ -4,7 +4,7 @@ VM_NAME=${1:-"k8s-master"}
 shift
 EXEC_COMMAND="$@"
 
-SSH_PORT=$(vagrant ssh-config ${VM_NAME} | grep Port | awk '{print $2}')
+SSH_PORT=$(vagrant ssh-config ${VM_NAME} | grep Port | awk '{print $2}') || { echo "failed to get ssh port of vm ${VM_NAME} "; exit 1 ; }
 if [ -z "${EXEC_COMMAND}" ] ; then
   sshpass -p vagrant \
       ssh -p ${SSH_PORT} -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null vagrant@127.0.0.1
